#!/bin/bash
CCRAFTD_CONFIG_NAME="acc.conf.base"
CCRAFTD_BINARY_FILE_NAME="ccraftd"

# generate VARS
GEN_CONF_ROOT_DIR=${BIN_DIR}/../gen-configs
GEN_CONF_DIR=${GEN_CONF_ROOT_DIR}/conf
GEN_ACC_CONF_DIR=${GEN_CONF_DIR}/acc
GEN_SUPERVISOR_CONF_FILE_PATH=${GEN_CONF_DIR}/acc-supervisor.conf
GEN_SUPERVISOR_CHILDREN_CONF_DIR=${GEN_CONF_DIR}/supervisor-children

# install VARS
INST_ROOT_DIR=/export/apps/access-control-center
INST_CONF_DIR=${INST_ROOT_DIR}/conf
INST_ACC_CONF_DIR=${INST_CONF_DIR}/acc
INST_SUPERVISOR_CONF_DIR=${INST_CONF_DIR}
INST_SUPERVISOR_CONF_FILE_PATH=${INST_SUPERVISOR_CONF_DIR}/acc-supervisor.conf
INST_SUPERVISOR_CHILDREN_CONF_DIR=${INST_CONF_DIR}/supervisor-children

# pack VARS
PACK_ROOT_DIR=${ROOT_DIR}/dist
PACK_BIN_DIR=${PACK_ROOT_DIR}/bin
PACK_CONF_ROOT_DIR=${ROOT_DIR}/dist/conf
PACK_ACC_CONF_DIR=${PACK_CONF_ROOT_DIR}/acc
PACK_CONF_SUPERVISOR_CHILDREN_DIR=${PACK_CONF_ROOT_DIR}/supervisor-children
